### ISSUE TITLE
TypeError: TextInputSequence must be str

### ISSUE THREAD

**Issue by RishabhMaheshwary** [PAIR-code/lit#202]
I ran the following command 
```
python -m lit_nlp.examples.glue_demo --port=5432 --quickstart
```
and got the following error:
```
 Traceback (most recent call last):
  File "/Users/rishabhmaheshwary/anaconda3/lib/python3.7/site-packages/lit_nlp/lib/wsgi_app.py", line 191, in __call__
    return self._ServeCustomHandler(request, clean_path)(environ,
  File "/Users/rishabhmaheshwary/anaconda3/lib/python3.7/site-packages/lit_nlp/lib/wsgi_app.py", line 176, in _ServeCustomHandler
    return self._handlers[clean_path](self, request)
  File "/Users/rishabhmaheshwary/anaconda3/lib/python3.7/site-packages/lit_nlp/app.py", line 75, in _handler
    outputs = fn(data, **kw)
  File "/Users/rishabhmaheshwary/anaconda3/lib/python3.7/site-packages/lit_nlp/app.py", line 184, in _get_preds
    preds = list(self._predict(data['inputs'], model, dataset_name))
  File "/Users/rishabhmaheshwary/anaconda3/lib/python3.7/site-packages/lit_nlp/app.py", line 138, in _predict
    inputs, dataset_name=dataset_name)
  File "/Users/rishabhmaheshwary/anaconda3/lib/python3.7/site-packages/lit_nlp/lib/caching.py", line 203, in predict_with_metadata
    results = self._predict_with_metadata(*args, **kw)
  File "/Users/rishabhmaheshwary/anaconda3/lib/python3.7/site-packages/lit_nlp/lib/caching.py", line 232, in _predict_with_metadata
    model_preds = list(self._model.predict_with_metadata(model_inputs))
  File "/Users/rishabhmaheshwary/anaconda3/lib/python3.7/site-packages/lit_nlp/api/model.py", line 190, in <genexpr>
    results = (scrub_numpy_refs(res) for res in results)
  File "/Users/rishabhmaheshwary/anaconda3/lib/python3.7/site-packages/lit_nlp/api/model.py", line 202, in _batched_predict
    yield from self.predict_minibatch(minibatch, **kw)
  File "/Users/rishabhmaheshwary/anaconda3/lib/python3.7/site-packages/lit_nlp/examples/models/glue_models.py", line 340, in predict_minibatch
    encoded_input = self._preprocess(inputs)
  File "/Users/rishabhmaheshwary/anaconda3/lib/python3.7/site-packages/lit_nlp/examples/models/glue_models.py", line 107, in _preprocess
    pad_to_max_length=True)
  File "/Users/rishabhmaheshwary/anaconda3/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 2520, in batch_encode_plus
    **kwargs,
  File "/Users/rishabhmaheshwary/anaconda3/lib/python3.7/site-packages/transformers/tokenization_utils_fast.py", line 378, in _batch_encode_plus
    is_pretokenized=is_split_into_words,
TypeError: TextInputSequence must be str
```

**Comment by iftenney** [comment]
Which version of transformers are you using? 

The demos in the current pip package are pinned to transformers==2.11.0 (see https://github.com/PAIR-code/lit/blob/main/environment.yml). We'll push a new release soon that updates this, but for now if you clone the LIT repo, the `dev` branch has the changes to work with the latest version (transformers=4.1.1).

**Comment by RishabhMaheshwary** [comment]
Thanks, it is working.
