### ISSUE TITLE
'ModulePassManager' object has no attribute 'add_loop_rotate_pass'

### ISSUE THREAD

**Issue by ambikasadhu1101** [PAIR-code/lit#229]
I have installed lit on python 3.8.3. Upon executing my custom file, i get the following error:

Traceback (most recent call last):
  File "C:\Users\Ambika Sadhu\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Ambika Sadhu\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ambika Sadhu\Desktop\lit\demo.py", line 9, in <module>
    from lit_nlp import dev_server
  File "C:\Users\Ambika Sadhu\anaconda3\lib\site-packages\lit_nlp\dev_server.py", line 21, in <module>
    from lit_nlp import app as lit_app
  File "C:\Users\Ambika Sadhu\anaconda3\lib\site-packages\lit_nlp\app.py", line 39, in <module>
    from lit_nlp.components import umap
  File "C:\Users\Ambika Sadhu\anaconda3\lib\site-packages\lit_nlp\components\umap.py", line 21, in <module>
    import umap
  File "C:\Users\Ambika Sadhu\anaconda3\lib\site-packages\umap\__init__.py", line 2, in <module>
    from .umap_ import UMAP
  File "C:\Users\Ambika Sadhu\anaconda3\lib\site-packages\umap\umap_.py", line 28, in <module>
    import numba
  File "C:\Users\Ambika Sadhu\anaconda3\lib\site-packages\numba\__init__.py", line 212, in <module>
    import numba.typed
  File "C:\Users\Ambika Sadhu\anaconda3\lib\site-packages\numba\typed\__init__.py", line 1, in <module>
    from .typeddict import Dict
  File "C:\Users\Ambika Sadhu\anaconda3\lib\site-packages\numba\typed\typeddict.py", line 23, in <module>
    def _make_dict(keyty, valty):
  File "C:\Users\Ambika Sadhu\anaconda3\lib\site-packages\numba\core\decorators.py", line 260, in njit
    return jit(*args, **kws)
  File "C:\Users\Ambika Sadhu\anaconda3\lib\site-packages\numba\core\decorators.py", line 183, in jit
    return wrapper(pyfunc)
  File "C:\Users\Ambika Sadhu\anaconda3\lib\site-packages\numba\core\decorators.py", line 210, in wrapper
    disp = dispatcher(py_func=func, locals=locals,
  File "C:\Users\Ambika Sadhu\anaconda3\lib\site-packages\numba\core\dispatcher.py", line 746, in __init__
    self.targetctx = self.targetdescr.target_context
  File "C:\Users\Ambika Sadhu\anaconda3\lib\site-packages\numba\core\registry.py", line 47, in target_context
    return self._toplevel_target_context
  File "C:\Users\Ambika Sadhu\anaconda3\lib\site-packages\numba\core\utils.py", line 277, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Ambika Sadhu\anaconda3\lib\site-packages\numba\core\registry.py", line 31, in _toplevel_target_context
    return cpu.CPUContext(self.typing_context)
  File "C:\Users\Ambika Sadhu\anaconda3\lib\site-packages\numba\core\base.py", line 259, in __init__
    self.init()
  File "C:\Users\Ambika Sadhu\anaconda3\lib\site-packages\numba\core\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\Ambika Sadhu\anaconda3\lib\site-packages\numba\core\cpu.py", line 47, in init
    self._internal_codegen = codegen.JITCPUCodegen("numba.exec")
  File "C:\Users\Ambika Sadhu\anaconda3\lib\site-packages\numba\core\codegen.py", line 1086, in __init__
    self._init(self._llvm_module)
  File "C:\Users\Ambika Sadhu\anaconda3\lib\site-packages\numba\core\codegen.py", line 1105, in _init
    self._mpm_cheap = self._module_pass_manager(loop_vectorize=False,
  File "C:\Users\Ambika Sadhu\anaconda3\lib\site-packages\numba\core\codegen.py", line 1147, in _module_pass_manager
    pm.add_loop_rotate_pass()
AttributeError: 'ModulePassManager' object has no attribute 'add_loop_rotate_pass'

Numba version: 0.52.0
Please let me know possible solutions to this.

**Comment by jameswex** [comment]
The error is in the numba library, which LIT installs due to the umap library's dependence on numba. What versions of python libraries are installed in your environment? There could be a version issue for some of the libraries depending on what versions LIT needs vs what versions are installed due to your other dependencies.

See https://github.com/ddangelov/Top2Vec/issues/108 for someone else having a similar issue outside of LIT and solving it by changing which version of numba was installed in the environment.

**Comment by ambikasadhu1101** [comment]
Thank you for the link! I resolved it with numba==0.50, pynndescent==0.4.8,umap-learn==0.4.6.
