### ISSUE TITLE
Missing "import os" in lit_nlp/examples/models/glue_models.py

### ISSUE THREAD

**Issue by glhr** [PAIR-code/lit#34]
Running `python -m lit_nlp.examples.quickstart_sst_demo --port=5432` from the Quickstart examples gives a `NameError: name 'os' is not defined` at the end of training:

```
Epoch 3/3
2104/2104 - 1664s - loss: 0.2828 - accuracy: 0.8850 - val_loss: 0.4176 - val_accuracy: 0.8221
Traceback (most recent call last):
  File "/home/nemo/miniconda3/envs/lit-nlp/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/nemo/miniconda3/envs/lit-nlp/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/nemo/lit/lit_nlp/examples/quickstart_sst_demo.py", line 60, in <module>
    app.run(main)
  File "/home/nemo/miniconda3/envs/lit-nlp/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/nemo/miniconda3/envs/lit-nlp/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/nemo/lit/lit_nlp/examples/quickstart_sst_demo.py", line 48, in main
    run_finetuning(model_path)
  File "/home/nemo/lit/lit_nlp/examples/quickstart_sst_demo.py", line 42, in run_finetuning
    model.save(train_path)
  File "/home/nemo/lit/lit_nlp/examples/models/glue_models.py", line 168, in save
    if not os.path.isdir(path):
NameError: name 'os' is not defined
```

This is easily fixed by adding `import os` in `lit_nlp/examples/models/glue_models.py`.

**Comment by jameswex** [comment]
Thanks for pointing this out. Fixed in https://github.com/PAIR-code/lit/pull/37
