### ISSUE TITLE
dataset showing None in LTI UI

### ISSUE THREAD

**Issue by tiru1930** [PAIR-code/lit#367]
I am seeing dataset as None in UI, Please find for my sample code that i am using

```
from abc import ABC
from absl import app
from absl import flags
import fasttext
from lit_nlp import dev_server
from lit_nlp import server_flags
from lit_nlp.api import model as lit_model
from lit_nlp.api import types as lit_types
from lit_nlp.api import dataset as list_dataset
import pandas as pd

FLAGS = flags.FLAGS
# flags.DEFINE_integer("port", 4321, 'What port to serve on.')


def train_model():
    model = fasttext.train_supervised("./data/pre_processed.csv", epoch=25, lr=1.0, dim=200, thread=12, wordNgrams=2,
                                      verbose=5)
    model.save_model("./model/fasttext_model_v1.bin")


def test_model():
    model = fasttext.load_model("./model/fasttext_model_v1.bin")
    df = pd.read_csv("./data/pre_processed.csv", sep='\t', names=["label", "text"])
    print(model.predict(df.iloc[:32].text.to_list()))
    print(model.get_sentence_vector(df.iloc[:32].text.to_list()[0]))
    print(model.get_line(df.iloc[:32].text.to_list()[0]))


class FastTextDataSet(list_dataset.Dataset):
    """Loader for fasttext development set."""

    LABELS = pd.read_csv("./data/pre_processed.csv", sep="\t", names=["label", "text"]).label.unique().tolist()

    def __init__(self, path):
        super().__init__()
        df = pd.read_csv(path, sep='\t', names=["label", "text"])
        self._examples = [{
            'premise': row['text'],
            'label': row['label'],
        } for _, row in df.iterrows()]

    def spec(self):
        return {
            'premise': lit_types.TextSegment(),
            'label': lit_types.CategoryLabel(vocab=self.LABELS)
        }


class FastTextModel(lit_model.Model, ABC):
    LABELS = pd.read_csv("./data/pre_processed.csv", sep="\t", names=["label", "text"])["label"].unique().tolist()

    def __init__(self, model_name_or_path):
        self.model = fasttext.load_model(model_name_or_path)

    def max_minibatch_size(self):
        return 32

    def predict_minibatch(self, inputs):
        outputs = self.model(inputs)
        output = {}
        output["probas"] = outputs[1]
        output["tokens"] = []
        output["cls_emb"] = []
        for text in inputs:
            outputs["tokens"].append(self.model.get_line(text))
            output["cls_emb"].append(self.model.get_sentence_vector(text))
        yield output

    def input_spec(self) -> lit_types.Spec:
        return {
            "sentence": lit_types.TextSegment(),
            "label": lit_types.CategoryLabel(vocab=self.LABELS, required=False)
        }

    def output_spec(self) -> lit_types.Spec:
        return {
            "tokens": lit_types.Tokens(),
            "probas": lit_types.MulticlassPreds(parent="label", vocab=self.LABELS),
            "cls_emb": lit_types.Embeddings()
        }


def main(_):
    models = {"fasttext": FastTextModel("./model/fasttext_model_v1.bin")}
    datasets = {"fasttext_dev": FastTextDataSet("./data/pre_processed.csv")}
    args = server_flags.get_flags()
    args["port"] = 5433
    lit_demo = dev_server.Server(models, datasets, **args)
    lit_demo.serve()


if __name__ == '__main__':
    # train_model()
    # test_model()
    app.run(main)

```

![lit](https://user-images.githubusercontent.com/12211287/120794014-44143880-c555-11eb-9e77-789fae4202da.png)

**Comment by jameswex** [comment]
Thanks for reaching out. Looks like there is a mismatch between the names of the required TextSegment in the dataset ("premise") versus the model ("sentence"). Just change the model to have the TextSegment be named "sentence" instead of "premise" and I think it should work as expected.

**Comment by tiru1930** [comment]
@jameswex  thank you , it fixed now, but not showing up, embedding distribution graph and lime explainable is giving below error 

```
I0604 19:36:17.963431 139923967416128 app.py:134] 1 of 1 inputs sent as IDs; reconstituting from dataset 'fasttext_dev'
I0604 19:36:17.963534 139923967416128 caching.py:221] CachingModelWrapper 'fasttext': misses (dataset=fasttext_dev): []
I0604 19:36:17.963578 139923967416128 caching.py:223] CachingModelWrapper 'fasttext': 0 misses out of 1 inputs
I0604 19:36:17.963617 139923967416128 caching.py:228] Prepared 0 inputs for model
I0604 19:36:17.963698 139923967416128 caching.py:230] Received 0 predictions from model
I0604 19:36:17.963754 139923967416128 lime_explainer.py:103] Found text fields for LIME attribution: ['sentence']
I0604 19:36:17.963804 139923967416128 lime_explainer.py:128] Explaining: WOOD PRODUCTS Wood Products 6 x 14 x 36, Douglas Fir, No. 1 & Better, Green, Rough Sawn, Surfaced 4 Sides 6 x 14 x 36, Douglas Fir, No. 1 & Better, Green, Rough Sawn, Surfaced 4 Sides ; WOOD PRODUCTS ; Wood Products ; 06x14x36DFNo1BTRSGRNROS4S ; Timbers Douglas Fir, Green, No. 1 & Better grade lumber. Often described as a 36 ft, 6 x 14 (nominal sizing), this product typically measures 5-1/2 in thick by 13-1/4 in wide. Appearance notes: Rough Sawn, Surfaced 4 Sides. 
W0604 19:36:17.970363 139923967416128 caching.py:183] CachingModelWrapper.predict() bypasses the cache - if this is not intended, use predict_with_metadata() instead to access cache via example IDs.
E0604 19:36:17.975048 139923967416128 wsgi_app.py:208] Uncaught error: Found input variables with inconsistent numbers of samples: [257, 9] 

 Traceback (most recent call last):
  File "/home/tiru/lit/lit_nlp/lib/wsgi_app.py", line 191, in __call__
    return self._ServeCustomHandler(request, clean_path, environ)(
  File "/home/tiru/lit/lit_nlp/lib/wsgi_app.py", line 176, in _ServeCustomHandler
    return self._handlers[clean_path](self, request, environ)
  File "/home/tiru/lit/lit_nlp/app.py", line 318, in _handler
    outputs = fn(data, **kw)
  File "/home/tiru/lit/lit_nlp/app.py", line 257, in _get_interpretations
    config=data.get('config'))
  File "/home/tiru/lit/lit_nlp/api/components.py", line 63, in run_with_metadata
    return self.run(inputs, model, dataset, model_outputs, config)
  File "/home/tiru/lit/lit_nlp/components/lime_explainer.py", line 141, in run
    seed=seed)
  File "/home/tiru/lit/lit_nlp/components/citrus/lime.py", line 162, in explain
    masks, outputs, sample_weight=distances)
  File "/home/tiru/anaconda3/envs/lit-nlp/lib/python3.7/site-packages/sklearn/linear_model/_ridge.py", line 762, in fit
    return super().fit(X, y, sample_weight=sample_weight)
  File "/home/tiru/anaconda3/envs/lit-nlp/lib/python3.7/site-packages/sklearn/linear_model/_ridge.py", line 545, in fit
    multi_output=True, y_numeric=True)
  File "/home/tiru/anaconda3/envs/lit-nlp/lib/python3.7/site-packages/sklearn/base.py", line 433, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/home/tiru/anaconda3/envs/lit-nlp/lib/python3.7/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/home/tiru/anaconda3/envs/lit-nlp/lib/python3.7/site-packages/sklearn/utils/validation.py", line 888, in check_X_y
    check_consistent_length(X, y)
  File "/home/tiru/anaconda3/envs/lit-nlp/lib/python3.7/site-packages/sklearn/utils/validation.py", line 320, in check_consistent_length
    " samples: %r" % [int(l) for l in lengths])
ValueError: Found input variables with inconsistent numbers of samples: [257, 9]

I0604 19:36:17.975469 139923967416128 _internal.py:225] 127.0.0.1 - - [04/Jun/2021 19:36:17] "POST /get_interpretations?model=fasttext&dataset_name=fasttext_dev&interpreter=LIME HTTP/1.1" 500 -

```

**Comment by jameswex** [comment]
Interesting. Is there error for the embedding projector the same ValueError or something different?

What does the return from the model predict function look like for some example data? Perhaps the data structures used in the "tokens" and "cls_emb" aren't what LIT is expecting. Does the basic prediction work (do you see correct results in the classification results module in the "Predictions" tab)?

**Comment by tiru1930** [comment]
there is no error while embedding projector , model.predict gives , Tuple[List[labels],List[probs]],,

below i shared predict_minibatch , where token is just normal space based regx tokens of input sentence, sentence vectors i vectroized form of sentence
```
    def predict_minibatch(self, inputs):
        # print(inputs)
        # outputs = self.model.predict(inputs[0]["sentence"])
        # output = {}
        # output["probas"] = outputs[1]
        # output["tokens"] = []
        # output["cls_emb"] = []
        # for text in inputs:
        #     outputs["tokens"].append(self.model.get_line(text))
        #     output["cls_emb"].append(self.model.get_sentence_vector(text))
        # yield output
        output = {"probas": self.model.predict(inputs[0]["sentence"])[1],
                  "label": self.model.predict(inputs[0]["sentence"])[0],
                  "tokens": self.model.get_line(inputs[0]["sentence"]),
                  "cls_emb": self.model.get_sentence_vector(inputs[0]["sentence"])}
        yield output

```

```
{'probas': array([0.99019891]), 'label': ('__label__66>65>1679>1691',), 'tokens': (['VF', 'CORPORATION', 'Dickies', 'Dickies', '1939RMS3832', 'Carpenter', 'Jeans,', '38', 'in', 'Waist,', '32', 'in', 'Inseam', 'L,', 'Moss', 'Green,', 'Relaxed', 'Dickies;', '1939RMS3832;', 'Carpenter', 'Jeans;', 'Jeans', 'Step', 'up', 'your', 'work', 'wear', 'game', 'with', 'a', 'pair', 'of', 'Dickies', 'relaxed', 'fit', 'straight', 'leg', 'carpenter', 'duck', 'jeans', 'that', 'quickly', 'became', 'a', 'five-star', 'customer', 'favorite.', 'the', 'combination', 'of', 'a', 'classic', 'carpenter', 'jean', 'with', 'tightly', 'woven', 'cotton', 'duck', 'make', 'this', 'pant', 'both', 'durable', 'and', 'comfortable', 'a', 'great', 'value', 'and', 'a', 'must', 'have', 'for', 'long', 'days', 'on', 'the', 'clock.', 'the', 'relaxed', 'fit', 'provides', 'extra', 'room', 'in', 'the', 'seat', 'and', 'thigh,', 'while', 'the', 'tapered', 'leg', 'makes', 'it', 'easy', 'to', 'fit', 'over', 'a', 'pair', 'of', 'work', 'boots.', 'hammer', 'loop', 'and', 'dual', 'tool', 'pockets', 'put', 'tools', 'within', 'easy', 'reach', 'so', 'you', 'can', 'work', 'all', 'day', 'without', 'running', 'back', 'and', 'forth', 'to', 'your', 'tool', 'box.', '</s>'], []), 'cls_emb': array([ 0.08043595, -0.02307   ,  0.00035395,  0.0504947 ,  0.11108944,
       -0.06540178, -0.07371125, -0.08703277,  0.03128601, -0.07178675,
        0.03109851, -0.03486339, -0.11960525,  0.03916796,  0.0008975 ,
        0.11712726, -0.05241439, -0.00556256,  0.11681285,  0.12696826,
       -0.03254239, -0.01328552,  0.08439945, -0.12605515, -0.00372616,
       -0.07122596,  0.15163033, -0.06959042,  0.09730244,  0.0344522 ,
       -0.00446524,  0.04382062, -0.03941821, -0.07095685, -0.08049572,
        0.04246201, -0.03889009,  0.03737019,  0.02405596,  0.02883488,
       -0.11102574, -0.12021715,  0.13412443, -0.03055867,  0.07440332,
       -0.05266901,  0.00776746,  0.01495982, -0.10730138,  0.11270092,
       -0.13824762,  0.03254433, -0.07182748, -0.00969893, -0.06597159,
        0.03656996, -0.03686427,  0.03100298, -0.02176676,  0.01107422,
        0.04201002,  0.14430617,  0.10535949,  0.0505395 ,  0.0090821 ,
        0.05410442, -0.08057026, -0.08010869,  0.03797854,  0.05058921,
        0.09782223,  0.01061741,  0.0727376 , -0.02798346,  0.0158957 ,
       -0.01232823,  0.09002604, -0.05248993,  0.14565846, -0.04175297,
        0.08557685, -0.0150498 ,  0.04279348, -0.08532883,  0.0479136 ,
       -0.01647406,  0.07954998,  0.10848313, -0.04464025,  0.09018161,
       -0.03177394, -0.2103219 ,  0.10286786, -0.13903019, -0.08835686,
       -0.14609066, -0.01802111, -0.06433751, -0.13065313,  0.00825025,
        0.02859951,  0.13859573, -0.01745162,  0.04501774,  0.04550237,
       -0.03416369, -0.14869593, -0.05949182,  0.01185591, -0.02471131,
       -0.01999396,  0.03863037,  0.00506107,  0.05239315, -0.01383921,
        0.11711334, -0.05334825, -0.1316254 ,  0.04852117, -0.07581269,
        0.06177449, -0.02579379, -0.02113658, -0.10420509, -0.05250693,
        0.06777203,  0.07532115,  0.00889798, -0.08612653, -0.03591467,
       -0.0223214 ,  0.04814789,  0.00919003, -0.01343076,  0.05826641,
       -0.05149259, -0.10763447, -0.04746587, -0.06400245,  0.12852107,
       -0.05211262,  0.15264899,  0.08464614,  0.04549982,  0.03627188,
       -0.03068904, -0.00903991,  0.00446643, -0.08883485, -0.01601942,
       -0.02484233, -0.11181808, -0.03108268, -0.04403802,  0.05639599,
        0.01542224, -0.07871497, -0.01059544,  0.08913702,  0.03411525,
       -0.14812158, -0.06027661,  0.11988163, -0.02851985, -0.1515732 ,
       -0.08991943, -0.04584902,  0.01389773, -0.04551989, -0.06648759,
       -0.10665048, -0.00898033,  0.07776166, -0.03477548,  0.10766589,
        0.10911973,  0.0835465 , -0.0962643 ,  0.19229294, -0.11438467,
        0.11318828, -0.02667461,  0.07811222,  0.06867034, -0.11277574,
        0.01798792, -0.00768585,  0.07927004, -0.0360497 , -0.08603775,
        0.01597784, -0.03581137, -0.05835809, -0.0402438 , -0.0992851 ,
       -0.0142586 , -0.01601976, -0.07115871, -0.03322146, -0.10974045],
      dtype=float32)}

```

**Comment by jameswex** [comment]
For the probs value in predictions return dictionary, it should be just a list of floats (with each entry being the score for the class with the corresponding index from the labels list you provided in the model output spec). You don't need to return a "label", as LIT will determine the label predicted based on the scores for each possible class returned.

**Comment by tiru1930** [comment]
@jameswex  i am sorry did not get 
in the above output probs is np array  {'probas': array([0.99019891]), its not dictonary

**Comment by jameswex** [comment]
The length of the probas array should be the same length as self.LABELS, with one score for each label. I think that is the issue.

**Comment by tiru1930** [comment]
Now i can see embedding projector  but, UI is crashing, I can't change screens to check explanations and other things I have total 348 labels on 6K samples

**Comment by jameswex** [comment]
We have scaling issues on large numbers of examples, especially in multiclass models with lots of possible classes. For now you can try with a smaller number of examples to see if that helps (try just 50 to see what happens, for example). We have a number of mitigations on the way to make the performance better for your use case.

**Comment by tiru1930** [comment]
```

0607 19:13:00.254899 140671368333120 caching.py:183] CachingModelWrapper.predict() bypasses the cache - if this is not intended, use predict_with_metadata() instead to access cache via example IDs.
E0607 19:13:00.259344 140671368333120 wsgi_app.py:208] Uncaught error: Found input variables with inconsistent numbers of samples: [257, 9] 

 Traceback (most recent call last):
  File "/home/tiru/lit/lit_nlp/lib/wsgi_app.py", line 191, in __call__
    return self._ServeCustomHandler(request, clean_path, environ)(
  File "/home/tiru/lit/lit_nlp/lib/wsgi_app.py", line 176, in _ServeCustomHandler
    return self._handlers[clean_path](self, request, environ)
  File "/home/tiru/lit/lit_nlp/app.py", line 318, in _handler
    outputs = fn(data, **kw)
  File "/home/tiru/lit/lit_nlp/app.py", line 257, in _get_interpretations
    config=data.get('config'))
  File "/home/tiru/lit/lit_nlp/api/components.py", line 63, in run_with_metadata
    return self.run(inputs, model, dataset, model_outputs, config)
  File "/home/tiru/lit/lit_nlp/components/lime_explainer.py", line 141, in run
    seed=seed)
  File "/home/tiru/lit/lit_nlp/components/citrus/lime.py", line 162, in explain
    masks, outputs, sample_weight=distances)
  File "/home/tiru/anaconda3/envs/lit-nlp/lib/python3.7/site-packages/sklearn/linear_model/_ridge.py", line 762, in fit
    return super().fit(X, y, sample_weight=sample_weight)
  File "/home/tiru/anaconda3/envs/lit-nlp/lib/python3.7/site-packages/sklearn/linear_model/_ridge.py", line 545, in fit
    multi_output=True, y_numeric=True)
  File "/home/tiru/anaconda3/envs/lit-nlp/lib/python3.7/site-packages/sklearn/base.py", line 433, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/home/tiru/anaconda3/envs/lit-nlp/lib/python3.7/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/home/tiru/anaconda3/envs/lit-nlp/lib/python3.7/site-packages/sklearn/utils/validation.py", line 888, in check_X_y
    check_consistent_length(X, y)
  File "/home/tiru/anaconda3/envs/lit-nlp/lib/python3.7/site-packages/sklearn/utils/validation.py", line 320, in check_consistent_length
    " samples: %r" % [int(l) for l in lengths])
ValueError: Found input variables with inconsistent numbers of samples: [257, 9]


```

while doing Explanations with Lime.. I am using Fasttext model

**Comment by tiru1930** [comment]
```
from abc import ABC
from absl import app
from absl import flags
import fasttext
from lit_nlp import dev_server
from lit_nlp import server_flags
from lit_nlp.api import model as lit_model
from lit_nlp.api import types as lit_types
from lit_nlp.api import dataset as list_dataset
import pandas as pd

FLAGS = flags.FLAGS


# flags.DEFINE_integer("port", 4321, 'What port to serve on.')


def train_model():
    model = fasttext.train_supervised("./data/pre_processed.csv", epoch=25, lr=1.0, dim=200, thread=12, wordNgrams=2,
                                      verbose=5)
    model.save_model("./model/fasttext_model_v1.bin")


def test_model():
    model = fasttext.load_model("./model/fasttext_model_v1.bin")
    df = pd.read_csv("./data/pre_processed.csv", sep='\t', names=["label", "text"])
    print(model.predict(df.iloc[:32].text.to_list()))
    print(model.get_sentence_vector(df.iloc[:32].text.to_list()[0]))
    print(model.get_line(df.iloc[:32].text.to_list()[0]))


class FastTextDataSet(list_dataset.Dataset, ABC):
    """Loader for fasttext development set."""

    LABELS = pd.read_csv("./data/pre_processed.csv", sep="\t", names=["label", "text"]).label.unique().tolist()

    def __init__(self, path):
        # super().__init__()
        df = pd.read_csv(path, sep='\t', names=["label", "text"]).iloc[:50]
        self._examples = [{
            'sentence': row['text'],
            'label': row['label'],
        } for _, row in df.iterrows()]

    def spec(self):
        return {
            'sentence': lit_types.TextSegment(),
            'label': lit_types.CategoryLabel(vocab=self.LABELS)
        }


class FastTextModel(lit_model.Model, ABC):
    LABELS = pd.read_csv("./data/pre_processed.csv", sep="\t", names=["label", "text"])["label"].unique().tolist()

    def __init__(self, model_name_or_path):
        self.model = fasttext.load_model(model_name_or_path)

    def max_minibatch_size(self):
        return 1

    def predict_minibatch(self, inputs):
        output = {"probas": self.model.predict(inputs[0]["sentence"], k=len(self.LABELS))[1],
                  "tokens_": self.model.get_line(inputs[0]["sentence"]),
                  "input_embs_": self.model.get_sentence_vector(inputs[0]["sentence"])}
        yield output

    def input_spec(self) -> lit_types.Spec:
        return {
            "sentence": lit_types.TextSegment(),
            "label": lit_types.CategoryLabel(vocab=self.LABELS, required=False)
        }

    def output_spec(self) -> lit_types.Spec:
        return {
            "tokens_": lit_types.Tokens(),
            "probas": lit_types.MulticlassPreds(parent="label", vocab=self.LABELS),
            "input_embs_": lit_types.Embeddings(),
        }


def main(_):
    models = {"fasttext": FastTextModel("./model/fasttext_model_v1.bin")}
    datasets = {"fasttext_dev": FastTextDataSet("./data/pre_processed.csv")}
    args = server_flags.get_flags()
    args["port"] = 5433
    lit_demo = dev_server.Server(models, datasets, **args)
    lit_demo.serve()


if __name__ == '__main__':
    # train_model()
    # test_model()
    app.run(main)
    # df = pd.read_csv("./data/pre_processed.csv", sep="\t", names=["label", "text"])
    # print(len(df.label.unique().tolist()))

```

**Comment by tiru1930** [comment]
thanks it can be closed i can make it work by deleting Cach and re installing it thank you @jameswex
