### ISSUE TITLE
SyntaxError: invalid syntax  mspec: lit_model.ModelSpec = m.spec()

### ISSUE THREAD

**Issue by paroque28** [PAIR-code/lit#8]
```
$ python3 -m lit_nlp.examples.quickstart_sst_demo --port=5432                                                                                                                           
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "~/lit/lit_nlp/examples/quickstart_sst_demo.py", line 20, in <module>
    from lit_nlp import dev_server
  File "~/lit/lit_nlp/dev_server.py", line 21, in <module>
    from lit_nlp import app as lit_app
  File "~/lit/lit_nlp/app.py", line 91
    mspec: lit_model.ModelSpec = m.spec()
         ^
SyntaxError: invalid syntax
```
Python Version
```
$ python3                                                    
Python 3.5.2 (default, Jul 17 2020, 14:04:10) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

Is this related with the python version?

**Comment by iftenney** [comment]
Quite possible. Can you try with python 3.7 or higher? (see https://github.com/PAIR-code/lit/blob/main/environment.yml#L17)

**Comment by paroque28** [comment]
Yes, that solved the issue
