### ISSUE TITLE
odd error running on colab

### ISSUE THREAD

**Issue by JINHXu** [PAIR-code/lit#976]
Hey there,

I got an odd error when running my code on colab

```
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    from lit_utils import *
  File "/content/lit_utils.py", line 27, in <module>
    from lit_nlp import dev_server
  File "/usr/local/lib/python3.8/dist-packages/lit_nlp/dev_server.py", line 21, in <module>
    from lit_nlp import app as lit_app
  File "/usr/local/lib/python3.8/dist-packages/lit_nlp/app.py", line 28, in <module>
    from lit_nlp.api import components as lit_components
  File "/usr/local/lib/python3.8/dist-packages/lit_nlp/api/components.py", line 20, in <module>
    from lit_nlp.api import dataset as lit_dataset
  File "/usr/local/lib/python3.8/dist-packages/lit_nlp/api/dataset.py", line 25, in <module>
    from lit_nlp.api import types
  File "/usr/local/lib/python3.8/dist-packages/lit_nlp/api/types.py", line 37, in <module>
    JsonDict = dict[str, Any]
TypeError: 'type' object is not subscriptable
```

the oddity would be that the same code runs perfectly fine on my computer and a week ago on colab, does anyone have a clue what might be going on? Thanks for your help!

Cheers,
Xu

**Comment by iftenney** [comment]
Hi Xu,

With the v0.5 release, LIT uses Python 3.9 and this line `dict[str, Any]` uses [PEP 585 typing](https://peps.python.org/pep-0585/) which was added in 3.9. Unfortunately, Colab is still stuck on an older version of Python - this is their issue to track: https://github.com/googlecolab/colabtools/issues/2165

See also the note in the notebook example: https://github.com/PAIR-code/lit/blob/main/lit_nlp/examples/notebooks/LIT_components_example.ipynb. For now, I'd recommend using a regular Jupyter environment with Python 3.9, or alternatively you could use an older version of LIT with `pip install lit-nlp==0.4.1`

**Comment by JINHXu** [comment]
Thanks, Ian! 🙏

**Comment by RyanMullins** [comment]
@JINHXu just a quick update on this, but Colab has now been updated to Python 3.10, so you should be able to use LIT v0.5 without issue. Please let us know if you find any regressions!

See https://github.com/googlecolab/colabtools/issues/3572
